/** Declaration file generated by dts-gen */

export function $(x: any): void;

export function $addToSet(x: any): void;

export function $and(x: any): any;

export function $bit(): any;

export function $currentDate(type: any): void;

export function $inc(value: any): void;

export function $max(value: any): void;

export function $min(value: any): void;

export function $mul(value: any): void;

export function $or(x: any): any;

export function $pop(x: any): void;

export function $pull(x: any): void;

export function $pullAll(x: any): void;

export function $push(x: any): void;

export function $rename(field: any): void;

export function $set(value: any): void;

export function $setOnInsert(value: any): void;

export function $slice(x: any): void;

export function $sort(x: any): void;

export function $timestamp(): void;

export function $unset(): void;

export function $xor(x: any): any;

export function flatten(value: any): any;

export function isOperator(obj: any): void;

export namespace Operators {
    function $currentDate(type: any): void;

    function $inc(value: any): void;

    function $max(value: any): void;

    function $min(value: any): void;

    function $mul(value: any): void;

    function $rename(field: any): void;

    function $set(value: any): void;

    function $setOnInsert(value: any): void;

    function $timestamp(): void;

    function $unset(): void;

}

